[package]
name = "echotool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["cargo"] }
env_logger = "0.10.1"
log = "0.4.20"
tokio = { version = "1.35.1", features = ["net", "signal", "time"] }
